groups:
  - name: example_alerts
    rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Hohe Fehlerquote erkannt"
          description: "Mehr als 1 Fehler pro Sekunde in den letzten 5 Minuten."
