global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'product'
    metrics_path: /product/metrics
    static_configs:
      - targets: ['traefik:80']

  - job_name: 'order'
    metrics_path: /order/metrics
    static_configs:
      - targets: ['traefik:80']

  - job_name: 'payment'
    metrics_path: /payment/metrics
    static_configs:
      - targets: ['traefik:80']

  - job_name: 'shop'
    metrics_path: /shop/metrics
    static_configs:
      - targets: ['traefik:80']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - 'alert.rules.yml'
