global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'docker-microservices'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: 'product|order|payment'
        action: keep
      - source_labels: [__address__]
        regex: '(.*):\d+'
        replacement: '${1}:8000'
        target_label: __address__
        action: replace
