scrape_configs:
- job_name: docker_logs
  docker_sd_configs:
    - host: unix:///var/run/docker.sock
      refresh_interval: 10s
      filters:
        - name: label
          values: ["logging=promtail"]  # nur Container mit diesem Label
  pipeline_stages:
    - docker: {}              # zerlegt Docker JSON-Log
  relabel_configs:
    - source_labels: ['__meta_docker_container_name']
      regex: '/(.*)'
      target_label: 'container'
    - source_labels: ['__meta_docker_container_log_stream']
      target_label: 'stream'
    - target_label: 'job'
      replacement: 'docker'
