server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_status]
        regex: running
        action: keep
      - source_labels: [__meta_docker_container_name]
        target_label: container
      - source_labels: [__meta_docker_container_image]
        target_label: image
      # Nutze entweder das Compose-Label oder als Fallback den Container-Namen
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: service_name
      - source_labels: [__meta_docker_container_name]
        target_label: service_name
        action: replace
        regex: ""
        replacement: "unknown_service"


