apiVersion: 1
datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
  
  - name: loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
      minInterval: "1s"
    version: 1
    editable: true
  
  - name: jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    jsonData:
      esVersion: 7
      esIndices: "jaeger-*"
      esTimeField: "@timestamp"
    version: 1
    editable: true
  
  - name: alertmanager
    type: Alertmanager
    access: proxy
    url: http://alertmanager:9093
    jsonData:
      apiVersion: 2
      alertmanagerVersion: "v2"
    version: 1
    editable: true