services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${PRODUCT_DB} # Wird nur beim ersten Start erzeugt, weitere per Init-Skript
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d # Siehe unten für mehrere DBs
    networks:
      - app

  product:
    build: ./product
    container_name: product
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${PRODUCT_DB}
    networks:
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.product.rule=PathPrefix(`/product`)"
      - "traefik.http.services.product.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.product-stripprefix.stripprefix.prefixes=/product"
      - "traefik.http.routers.product.middlewares=product-stripprefix@docker"

  order:
    build: ./order
    container_name: order
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${ORDER_DB}
    networks:
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.order.rule=PathPrefix(`/order`)"
      - "traefik.http.services.order.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.order-stripprefix.stripprefix.prefixes=/order"
      - "traefik.http.routers.order.middlewares=order-stripprefix@docker"

  payment:
    build: ./payment
    container_name: payment
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${PAYMENT_DB}
    networks:
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.payment.rule=PathPrefix(`/payment`)"
      - "traefik.http.services.payment.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.payment-stripprefix.stripprefix.prefixes=/payment"
      - "traefik.http.routers.payment.middlewares=payment-stripprefix@docker"

  shop:
    build: ./shop
    container_name: shop
    depends_on:
      - product
      - order
      - payment
    ports:
      - "8004:8000"
    networks:
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shop.rule=PathPrefix(`/shop`)"
      - "traefik.http.services.shop.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.shop-stripprefix.stripprefix.prefixes=/shop"
      - "traefik.http.routers.shop.middlewares=shop-stripprefix@docker"

networks:
  app:
    external: true # Von Terraform erzeugt, für Monitoring/Tracing

volumes:
  mariadb_data:
